__default__:
    job-name: "{rule}"
    partition: "exacloud"
    nodes: 1
    cpus-per-task: 1
    time: "00:30:00"
    mem: 8G
    error: "jobs/{rule}/{rule}_%j.err"
    out: "jobs/{rule}/{rule}_%j.out"
cellranger_multi:
    mem: 64G
    time: "8:00:00"
    cpus-per-task: 8
cellranger_count:
    mem: 64G
    time: "8:00:00"
    cpus-per-task: 8
